### ISSUE TITLE
[Feature/login] 로그인 기능 구현 계획

### ISSUE THREAD

**Issue by Baeminseo** [4teamDBorganization/passaggio#15]
## 어떤 기능인가요?

> 회원가입 후 로그인 되도록 구현
   회원 DB 에서 값을 받아와 입력된 값과 비교 후 일치하면 로그인 되도록 구현

## 📝 작업 진행 체크리스트

- [x] MVC 모델 준수
- [x] 콘솔 출력
- [x] 최종 구현

< 클래스 설명 >
- controller. LoginController : loginService 연결용
- mapper. LoginMapper : login 쿼리문, 메소드 매핑
- models.login. LoginService : 데이터 베이스 연결
- myPage. MypageService : mypage 메인용 ( 수정 필요 )
- view.login.Login : 사용자 정보 입력 받기 및 실질적인 기능 구현

## ✅ 테스트 결과(이미지)(선택)
> LoginController

![스크린샷(7120)](https://github.com/4teamDBorganization/passaggio/assets/106863692/2d1153e0-5f36-4308-8efd-280bdb3dc9cc)
![스크린샷(7121)](https://github.com/4teamDBorganization/passaggio/assets/106863692/ad03df8d-e131-4cf9-87e4-197d2afcb3a7)

> LoginMapper

![스크린샷(7122)](https://github.com/4teamDBorganization/passaggio/assets/106863692/8e516f28-6d18-4ec4-b28a-658869d42a45)

> LoginService

![스크린샷(7123)](https://github.com/4teamDBorganization/passaggio/assets/106863692/1e6890c6-1b9b-4b71-b957-5297867622f8)

> Login

![스크린샷(7124)](https://github.com/4teamDBorganization/passaggio/assets/106863692/8291bf95-3f58-413f-96ff-2dfd084644a7)

**Comment by hyojunahn111** [comment]
다들 확인하셔서 닫겠습니다.
