### ISSUE TITLE
[Feature/playlist] 플레이리스트 전체 조회

### ISSUE THREAD

**Issue by sb-77** [4teamDBorganization/passaggio#17]
## 🛠️ 기능 설명
다른 모든 유저의 플레이리스트를 조회할 수 있는 기능을 추가한다.

다른 유저의 플레이리스트를 조회할 때에는 플레이리스트에 대한 노래 추가, 노래 삭제에 대한 기능을 제한한다.

## 📝 작업 진행 체크리스트

- [ ] MVC 모델 준수
- [ ] 콘솔 출력
- [ ] 최종 구현

## 📚 참고 자료(선택)
>

## ✅ 테스트 결과(이미지)(선택)
>

**Comment by hyojunahn111** [comment]
기능 제작 다들 확인하셨고 merge해서 닫겠습니다.
