### ISSUE TITLE
[Feature/playlist] 플레이리스트 내부 노래 추가

### ISSUE THREAD

**Issue by do0ik** [4teamDBorganization/passaggio#20]
## 🛠️ 기능 설명
플레이리스트와 관련된 DB 테이블은 아래와 같다.

> 플레이리스트 : 번호 /  회원번호 / 리스트 이름 / 소개
> 리스트내용 :  플레이리스트 번호 / 노래 번호
> 노래정보 : 번호 / 가수 / 제목 / 링크 / 소개

1. 노래(가수, 제목)에 대한 사용자 입력을 받은 후 해당 키워드들에 대한
    유튜브 최상단 결과의 링크를 크롤링 해 노래정보를 완성한다.

2. 생성된 노래 번호를 리스트 번호와 함께 리스트 내용 테이블에 저장해
    플레이리스트 - 노래정보 테이블 간 데이터 연결을 완성한다.

## 📝 작업 진행 체크리스트

- [x] MVC 모델 준수
- [x] 콘솔 출력
- [x] 최종 구현

## 📚 참고 자료(선택)
>
사용 라이브러리 (의존성 주입)
Jsoup 1.17.2 : HTML 태그 파싱
Gson 2.10.1 : JSON 데이터 파싱

## ✅ 테스트 결과(이미지)(선택)
>

> 유튜브 영상 재생 시 링크 형식 : https://www.youtube.com/watch?v=비디오아이디

Jsoup과 Gson 라이브러리를 이용해 "가수 제목"의 키워드로 검색 시 나타나는
유튜브 검색 결과 최상단 동영상의 비디오아이디를 크롤링 하였음

![image](https://github.com/4teamDBorganization/passaggio/assets/133643805/aa31f257-fd1e-4806-be05-1260e5abfb69)

**Comment by Baeminseo** [comment]
주석으로 설명해주셔서 잘 와닿네요~ 수고하셨습니다!

**Comment by hyojunahn111** [comment]
확인했습니다!~

**Comment by hyojunahn111** [comment]
기능 제작 다들 확인하셨고 merge해서 닫겠습니다.
