### ISSUE TITLE
[Feature/signup2] 회원가입시에 아이디가 중복 됐을 때 그 즉시 나오도록 변경

### ISSUE THREAD

**Issue by hyojunahn111** [4teamDBorganization/passaggio#21]
## 🛠️ 기능 설명
> 중복 기능

## 📝 작업 진행 체크리스트

- [X] MVC 모델 준수
- [X] 콘솔 출력
- [X] 최종 구현

## 📚 참고 자료(선택)
>

## ✅ 테스트 결과(이미지)(선택)
>
![image](https://github.com/4teamDBorganization/passaggio/assets/59754350/39d7e8cc-aa84-4fee-a216-8e11b75c19f1)

--> 사용하지 않는 부분 주석 후

![image](https://github.com/4teamDBorganization/passaggio/assets/59754350/e1ad8729-c914-486b-b863-f8cecd38a2b4)

--> SignUpController.class를  SignUp.java에서 사용할 수 있게 선언하고
      밑에 있던 Map<String, String> parameter = new HashMap<>(); 위로 올림
      후에 컨트롤러에 있던 내용을 옮김

**Comment by Baeminseo** [comment]
확인했습니다~ 이어서 로그인 기능 세부화 할게요!

**Comment by hyojunahn111** [comment]
기능 제작 다들 확인해주셨고 merge해서 닫겠습니다.
