### ISSUE TITLE
[Feature/user] user 브랜치 병합 시 발생한 회원가입 코드 중복 수정

### ISSUE THREAD

**Issue by Baeminseo** [4teamDBorganization/passaggio#23]
## 어떤 버그인가요?

> user 브랜치 병합 시 전에 작성한 코드끼리 충돌하여 코드 중복 현상 발생

## 어떤 상황에서 발생한 버그인가요?

> user 브랜치 병합 시도

## 예상 결과

> Application 클래스 : 불필요한 주석처리 코드 삭제
![스크린샷(7127)](https://github.com/4teamDBorganization/passaggio/assets/106863692/c457dae6-550d-4e5c-9666-b02f421069e8)

> SignUpController 클래스 : 회원번호 자동으로 생성되게 입력값을 받지 않도록 수정
![스크린샷(7128)](https://github.com/4teamDBorganization/passaggio/assets/106863692/1a24bdf7-362f-4d3e-ae7d-194a1877acd7)

> SignUp 클래스 : 회원아이디 중복체크 하는 과정에서 중복으로 회원아이디 물어보는 코드 제거
![스크린샷(7129)](https://github.com/4teamDBorganization/passaggio/assets/106863692/a37a3ff4-e3b7-48c2-ac0a-9f03e08f70fb)

**Comment by hyojunahn111** [comment]
확인했습니다~
