### ISSUE TITLE
[Bug/playlist] 크롤링 중 일부 노래 추가 시 예외

### ISSUE THREAD

**Issue by do0ik** [4teamDBorganization/passaggio#24]
## 🚨버그 설명
> 
노래 추가 시 View 클래스 내 crawl 메소드 실행 중 NullPointerException 발생

## ⏺️ 어떤 상황에서 발생한 버그인가요?
> 
1. crawl 메소드는 각 사용자에게 일정한 결과를 반환해주기 위해 입력된 가수와 제목의 모든 공백을 제거 후 유튜브에 request를 보냄

2. 유튜브는 잘못된 입력으로 예측되는 검색어에 대해 자동 수정 후 이 사실을 출력함 (예시 - 아래 이미지)

![image](https://github.com/4teamDBorganization/passaggio/assets/133643805/7a77eb29-0337-45cb-85c4-df232306626c)

## ❗ 예상 결과
> 
try-catch 구문을 통해 NullPointerException 발생 시

두 번째 JSON 배열 요소를 파싱할 수 있도록 수정

## 📚 참고할만한 자료(선택)
>

**Comment by hyojunahn111** [comment]
![image](https://github.com/4teamDBorganization/passaggio/assets/59754350/1a3fcbfb-04c9-42bc-88dd-217b9f2f8607)
이게 첫 번째 동영상으로 체크 되는건ㄷ가요?

**Comment by do0ik** [comment]
> ![image](https://private-user-images.githubusercontent.com/59754350/322172854-1a3fcbfb-04c9-42bc-88dd-217b9f2f8607.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMDE3NzYsIm5iZiI6MTcxMzAwMTQ3NiwicGF0aCI6Ii81OTc1NDM1MC8zMjIxNzI4NTQtMWEzZmNiZmItMDRjOS00MmJjLTg4ZGQtMjE3YjlmMmY4NjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDA5NDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MDgwOWY2ZDU2YmI4NDUxYjAzMGE3NjA2ODllZTQwMDZhNzM4MDAxYmY3OTljNjdiYzlkYzM0ZGI0YzNmNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.smq2eM8WtGDzki6BD07hSIsrjxZW6HIYyY-LnZ6n2Os) 이게 첫 번째 동영상으로 체크 되는건ㄷ가요?

비슷합니다.

[평시]
다음과 같이 contents 배열의 첫 객체에
**videoRenderer 객체**들이 담겨있습니다. 저희는 그 속 videoId가 필요하고요

![image](https://github.com/4teamDBorganization/passaggio/assets/133643805/1e1af7a5-1188-4064-9655-ee750ecabc95)


[검색어 자동 수정 시]

다음과 같이 contents 배열의 첫 객체에
**검색어 자동 수정 정보**를 담은 **showingResultsForRenderer** 객체들이 담겨있어 이런 처리가 추가되어야 하는 상황입니다.

![image](https://github.com/4teamDBorganization/passaggio/assets/133643805/493712fc-a8e9-4f74-b6c5-785440b473c9)

**Comment by hyojunahn111** [comment]
확인했습니다. 저런 처리는 수작업을 해야하는 상황인가요?

**Comment by do0ik** [comment]
@hyojunahn111 

네, 저는 아래와 같이 처리했습니다.

검색어 자동 수정 시에는 contents 배열의 첫 번째가 아닌 두 번째부터 videoRenderer 객체들이 출력됩니다.
 
평소와 같이 videoRenderer 객체에 접근했다가 NullPointerException 발생 시 검색어 자동 수정이 일어난 것으로 판단합니다.

이에 대해 catch 구문을 통해 다시 contents 배열 두 번째 요소에서 videoRenderer 객체에 접근하도록 합니다.

![image](https://github.com/4teamDBorganization/passaggio/assets/133643805/237cba20-d7da-4fc7-93ff-2e69c7d54079)

**Comment by hyojunahn111** [comment]
@do0ik 
음 보다보니까 한 가지 질문이 생겼는데
가끔 유튜브를 틀다보면 첫 번째 동영상으로 광고가 나오는 경우가 생기는데 그런 경우에는
예외처리를 한 번 더 해줘야하는건가요?

**Comment by do0ik** [comment]
@hyojunahn111 

애드블럭을 쓰다보니까 그 부분을 생각을 못했네요;; 버그 이슈로 올리겠습니다.

먼저 광고 동영상이 일반 동영상과 같은 데이터 형식으로 출력되는지 확인해봐야 할 것 같습니다.

만약 같다면 동영상 제목에 사용자가 입력한 가수나 제목 문자열이 포함되는지 확인하는 방안으로 가야할 것 같네요
