### ISSUE TITLE
[Feature/playlist] 플레이리스트 내부 노래 재생

### ISSUE THREAD

**Issue by do0ik** [4teamDBorganization/passaggio#25]
## 🛠️ 기능 설명
> 
플레이리스트 노래 추가와 동시에 크롤링을 통해 얻은 videoId 값을 유튜브 영상 재생 링크 문자열 완성 후

사용자 PC의 기본 브라우저를 통해 실행해 노래를 재생

## 📝 작업 진행 체크리스트

- [x] MVC 모델 준수
- [x] 콘솔 출력
- [x] 최종 구현

## 📚 참고 자료(선택)
>
[java.awt.Desktop / void browse(URI uri)](https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/java/awt/Desktop.html#browse(java.net.URI))

## ✅ 테스트 결과(이미지)(선택)
>

**Comment by hyojunahn111** [comment]
기능 제작 다들 확인하셨고 merge해서 닫겠습니다.
