### ISSUE TITLE
[Feature/playlist] 플레이리스트 전체 재생 및 셔플

### ISSUE THREAD

**Issue by do0ik** [4teamDBorganization/passaggio#26]
## 🛠️ 기능 설명
> 
유튜브는 비로그인 상태에서도 여러 videoId 값을 전달해 재생목록을 생성할 수 있는 URL 쿼리를 제공한다.

이를 활용해 플레이리스트 전체 재생 기능을 추가한다.

추가로, 전달하는 videoId 값의 순서에 따라 재생목록 내 영상들의 순서가 바뀌는 점을 이용해 셔플 기능을 구현한다.

## 📝 작업 진행 체크리스트

- [x] MVC 모델 준수
- [x] 콘솔 출력
- [x] 최종 구현

## 📚 참고 자료(선택)
>
[여러 videoId를 전달받는 유튜브 도메인 & 쿼리](https://www.labnol.org/internet/create-youtube-playlists/28827/#create-youtube-playlists-on-the-fly)

## ✅ 테스트 결과(이미지)(선택)
>
[ 순차 재생 테스트 결과 ]

![순차재생](https://github.com/4teamDBorganization/passaggio/assets/133643805/f4381474-a979-46b2-b097-23f685e136f9)

**Comment by Baeminseo** [comment]
기능 되게 좋네요! 참고하겠습니다~

**Comment by hyojunahn111** [comment]
기능 제작 다들 확인하셨고 merge해서 닫겠습니다.
