### ISSUE TITLE
[Feature/user] 회원가입 중복 확인, 조건 추가 

### ISSUE THREAD

**Issue by Baeminseo** [4teamDBorganization/passaggio#27]
## 🛠️ 기능 설명
> 회원가입 시 아이디와 닉네임 중복 확인 기능과 비밀번호 조건 추가 및 성별 오류 사항 잡기

## 📝 작업 진행 체크리스트

- [x] MVC 모델 준수
- [x] 콘솔 출력
- [x] 최종 구현

## ✅ 테스트 결과(이미지)(선택)
> SignUpContoller 클래스 : 닉네임 중복 확인 메서드 
![image](https://github.com/4teamDBorganization/passaggio/assets/106863692/8f87a55b-2313-4c1c-b669-4b161fe32586)

> SignUpService 클래스 : 닉네임 중복 확인 메서드
![image](https://github.com/4teamDBorganization/passaggio/assets/106863692/6b10282b-9af5-40c6-a102-1e1f08de7899)

> LoginMapper 인터페이스 : 닉네임 중복 확인 값 추가
![image](https://github.com/4teamDBorganization/passaggio/assets/106863692/fcb97c41-b756-4cde-a5dc-051f67497128)

> LoginMapper.xml : 닉네임 중복 체크 SQL 작성
![image](https://github.com/4teamDBorganization/passaggio/assets/106863692/a8dd2284-ecd4-4ca1-a1f5-7cf8c6700a40)

> sign 클래스 : 비밀번호 조건, 닉네임 중복 확인, 성별 오류 잡기 
![image](https://github.com/4teamDBorganization/passaggio/assets/106863692/15c96a8b-ab0e-4f73-b14b-39b7c07e05b8)
![image](https://github.com/4teamDBorganization/passaggio/assets/106863692/621120a8-e735-4dab-ab09-5737080d4e84)
![image](https://github.com/4teamDBorganization/passaggio/assets/106863692/4124a612-93cf-4f7d-b2a0-bfaed1a14b9a)
![image](https://github.com/4teamDBorganization/passaggio/assets/106863692/e3abe023-689a-42a8-a502-98e0a8e1c4fa)

**Comment by hyojunahn111** [comment]
중복기능 확인했습니다~
