### ISSUE TITLE
[Feature/user] 로그인 시 어떤 사람이 로그인했는지 정보 출력

### ISSUE THREAD

**Issue by hyojunahn111** [4teamDBorganization/passaggio#30]
## 🛠️ 기능 설명
> 로그인 시 어떤 사람이 로그인했는지 정보 출력

## 📝 작업 진행 체크리스트

- [x] MVC 모델 준수
- [x] 콘솔 출력
- [x] 최종 구현

## 📚 참고 자료(선택)
>

## ✅ 테스트 결과(이미지)(선택)
>
![image](https://github.com/4teamDBorganization/passaggio/assets/59754350/753d2be2-3839-449f-8d6c-c794a328f6bb)
id로 닉네임을 추출하게 설정하고

![image](https://github.com/4teamDBorganization/passaggio/assets/59754350/9ce4cd05-5f43-491f-b891-5cffe0f340cb)

![image](https://github.com/4teamDBorganization/passaggio/assets/59754350/f3cb05e0-a109-4527-bec4-a7228efcd567)
저장한 닉네임을 String으로 반환

![image](https://github.com/4teamDBorganization/passaggio/assets/59754350/686e4462-9d7a-4a49-942c-68ab04d9ea2b)
후에 출력

**Comment by Baeminseo** [comment]
닉네임 추출하는거 좋네요! 다른 곳에서도 이용할 수 있을 것 같아요

**Comment by hyojunahn111** [comment]
기능 제작 다들 확인해주셨고 merge해서 닫겠습니다.
