### ISSUE TITLE
[Bug/playlist] 크롤링 중 여러 케이스(검색어 자동 수정, 광고 출력 등) 동시 발생 시 예외

### ISSUE THREAD

**Issue by do0ik** [4teamDBorganization/passaggio#31]
## 🚨버그 설명
> 
검색어 자동 수정이 발생함과 동시에 광고 동영상이 최상단에 출력될 시 NullPointerException 발생

## ⏺️ 어떤 상황에서 발생한 버그인가요?
> 
기존에는 검색어 자동 수정 발생 시 JSON 데이터 배열의 두 번째 요소로 밀려난 동영상 정보에 접근하도록 하였음

해당 로직은 광고나 쇼츠 등 다른 요소가 단일로 최상단에 출력되는 경우에도 적용이 가능했으나

예를 들어 검색어 자동 수정과 광고 출력이 동시에 발생하는 경우 동영상 정보가 JSON 데이터 배열의 세 번째 혹은 더 이후로 밀려나 다시 NullPointerException이 발생함 (예시 - 아래 이미지)

![image](https://github.com/4teamDBorganization/passaggio/assets/133643805/4d419312-160f-40ca-8752-26e6e1a2eeb8)

## ❗ 예상 결과
> 
try-catch 구문을 반복 수행해 NullPointerException 발생 시

JSON 배열 요소에서 접근할 인덱스를 1씩 증가시킨다

## 📚 참고할만한 자료(선택)
>

**Comment by hyojunahn111** [comment]
확인했습니다.
