### ISSUE TITLE
[Feature/user2] 메인페이지에서 프로그램 종료 시 오류 발생

### ISSUE THREAD

**Issue by hyojunahn111** [4teamDBorganization/passaggio#45]
## 어떤 버그인가요?

> 메인페이지에서 프로그램 종료 시 오류 발생

## 어떤 상황에서 발생한 버그인가요?

> 메인페이지에서 프로그램 종료 시 오류 발생

## 예상 결과

> 

## 참고할만한 자료(선택)
>
![image](https://github.com/4teamDBorganization/passaggio/assets/59754350/66a1df1e-e3f7-49c3-a574-d6a64ebe6b3b)

**Comment by hyojunahn111** [comment]
![image](https://github.com/4teamDBorganization/passaggio/assets/59754350/e6f38590-e441-4b2c-aa30-cacae458fb72)
종료 클릭 시 프로그램을 종료 시켜버림

**Comment by Baeminseo** [comment]
저도 이거 발견했었는데 수정해주셨네요! 아주 좋습니다!!
