### ISSUE TITLE
[Feature/playlist] 로그인 기능 - 플레이리스트 기능 간 회원정보 연동

### ISSUE THREAD

**Issue by do0ik** [4teamDBorganization/passaggio#49]
## 🛠️ 기능 설명
> 
로그인 기능 - 플레이리스트 기능 간 회원정보 연동

## 📝 작업 진행 체크리스트

- [x] MVC 모델 준수
- [x] 콘솔 출력
- [x] 최종 구현

## 📚 참고 자료(선택)
>

## ✅ 테스트 결과(이미지)(선택)
>

**Comment by hyojunahn111** [comment]
확인했습니다
